wiki/encyclopedia/urls.py
from collections import namedtuple
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.wiki_page, name="wiki_page"),
    path("search/", views.search_page, name="search_page"),
    path("new_page/", views.new_page, name="new_page"),
    path("edit_page/<str:title>", views.edit_page, name="edit_page"),
    path("random_page/", views.random_page, name="random_page"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/forms.py
""" Forms for the app. """
from django import forms
from django.forms.fields import CharField
from django.forms.widgets import Input, Textarea

# class SearchForm(forms.Form):
#     search = forms.CharField()

class NewEntry(forms.Form):
    title = forms.CharField(max_length=80)
    # content = forms.Textarea()
    content = forms.CharField(widget=forms.Textarea)
    # foo = forms.TextInput()

class EditEntry(forms.Form):
    content = forms.CharField(widget=forms.Textarea)
    

wiki/encyclopedia/views.py
import markdown2 as md2
from random import choice
from django.shortcuts import render, redirect

from . import util
from .forms import NewEntry, EditEntry

def index(request):
    """Index page of the website."""
    context = {
        'entries': util.list_entries()
    }
    return render(request, "encyclopedia/index.html", context=context)

def wiki_page(request, title):
    """Render a requested page."""
    context = {
        'title': title,
        'content': None,
    }
    try:
        context['content'] = md2.markdown(util.get_entry(title))
    except:
        return render(request, 'encyclopedia/404.html', context=context)

    if context['content'] == None:
        return render(request, 'encyclopedia/404.html', context=context)
    else:
        return render(request, 'encyclopedia/wiki_page.html', context=context)

def random_page(request):
    """Choose a random page and redirect the user to it."""
    entries = util.list_entries()
    random_entry = choice(entries)
    return redirect('encyclopedia:wiki_page', random_entry)

def search_page(request):
    """Search for a page with either full name or slice of it."""
    if request.method == "POST":
        entries = util.list_entries()
        # Display the page if names match exactly
        if request.POST['q'] in entries:
            # wiki_page(request, request.POST['q'])
            return redirect('encyclopedia:wiki_page', request.POST['q'])
        
        # Show a page with the search results if any
        matches = []
        for entry in entries:
            if request.POST['q'] in entry:
                matches.append(entry)
        if matches:
            return render(request, 'encyclopedia/search.html', {'entries': matches})
        else:
            context={'title': request.POST['q']}
            return render(request, 'encyclopedia/404.html', context)

def new_page(request):
    """New page for any user to create."""
    if request.method == "POST":
        form = NewEntry(request.POST)
        if form.is_valid():
            title, content = form.cleaned_data['title'], form.cleaned_data['content']
            if title not in util.list_entries():
                util.save_entry(title, content)
                return redirect('encyclopedia:wiki_page', title)
            else:
                return render(request, 'encyclopedia/new_page.html', {
                    'form': form,
                    'error': True})

    else:
        form = NewEntry()
        return render(request, 'encyclopedia/new_page.html', {
            'form': form,
            'error': False})

def edit_page(request, title):
    if request.method == "POST":
        form = EditEntry(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            util.save_entry(title, content)
            return redirect('encyclopedia:wiki_page', title)
    
    else:
        entry = util.get_entry(title)
        form = EditEntry({'content': entry})
        return render(request, 'encyclopedia/edit_page.html', context={
            'entry': title,
            'form': form})

wiki/encyclopedia/templates/encyclopedia/edit_page.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}Edit page - {{ entry }}{% endblock %}

{% block body %}
    <form id="entry-form" action="#" method="POST">
        <h1>Edit {{ entry }} page</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <input id="button" type="submit" value="Save">
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1 style="font-size: 28px; text-align: center;">All Pages</h1>
    <ul id="index-list">
        {% for entry in entries %}
            <li id="index-list-item"><a href="{% url 'encyclopedia:wiki_page' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="layout-grid">
            <!-- <div id="header-grid">
                Placeholder
            </div> -->
            <div id="nav-grid">
                <h2 style="text-align: center;">Wiki</h2>
                <form action="{% url 'encyclopedia:search_page' %}" method="POST">
                    {% csrf_token %}
                    <input id="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div id="flex-container">
                    <div>
                        <a href="{% url 'encyclopedia:index' %}">Home</a>
                    </div>
                    <div>
                        <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                    </div>
                    <div>
                        <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                    </div>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div id="main-grid">
                {% block body %}
                {% endblock %}
            </div>
            <footer>
                <div>
                    Made by:
                    <a href="https://www.github.com/val-h" target="_blank">val-h</a>
                </div>
            </footer>
        </div>
    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}Create New Page{% endblock %}

{% block body %}
<!-- Form goes here -->
{% if error %}
<!-- Warrning element with css for later -->
<h3 style="color: rgb(240, 132, 0);">A page with that name already exists!</h3>
{% endif %}
<form id="entry-form" action="{% url 'encyclopedia:new_page' %}" method="POST">
        <h1>Create a new page</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <input id="button" type="submit" value="Create Page">
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}Search{% endblock %}

{% block body %}
    {% for entry in entries %}
        <div style="margin: 15px 20px;">
            <a href="{% url 'encyclopedia:wiki_page' entry %}">{{ entry }}</a>
        </div>
    {% empty %}
        <h3 style="text-align: center; margin-top: 100px; font-size: 36px;">
            No Results found!
        </h3>
    {% endfor %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/wiki_page.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
    <!-- <h1>{{ title }}</h1> -->
    <!-- <hr> -->
    <p>
        {{ content|safe }}
    </p>
    <hr>
    <a id="edit-link" href="{% url 'encyclopedia:edit_page' title %}">Edit Content</a>
{% endblock %}